function getRandomEvent() {
  const events = [
    "You enter a mysterious forest where ancient trees whisper secrets of lost civilizations, their voices carried by the cool night breeze.",
    "A sudden gust of wind carries the scent of pine, damp earth, and a hint of something exotic as you approach a shadowy clearing.",
    "Moonlight filters through a dense canopy of leaves, casting ethereal, silvery patterns on the forest floor and hinting at hidden wonders.",
    "A sudden chill runs down your spine as thick fog envelops the path, reducing your surroundings to ghostly silhouettes.",
    "Distant, mournful howls echo among the trees—a somber reminder that unseen dangers lurk in the darkness.",
    "A soft, ethereal glow emanates from a cluster of bioluminescent mushrooms, their light gently guiding your cautious steps forward.",
    "The rustle of leaves and subtle cracking of twigs suggest that unseen creatures are stealthily watching your every move.",
    "An eerie silence falls over the forest, the usual sounds of nature muted as if nature itself is holding its breath.",
    "A babbling brook appears from behind a curtain of ferns, its crystal waters shimmering with hints of magic and mystery.",
    "The ground beneath your feet trembles softly, as though the very earth is awakening to ancient, forgotten forces.",
    "A burst of vibrant colors explodes in the air—a fleeting, mesmerizing display of nature's hidden, untamed magic.",
    "Whispering winds carry fragmented words in an archaic tongue, leaving you to puzzle over their mysterious meaning.",
    "A gentle symphony of birdsong, rustling leaves, and distant animal calls creates a harmonious lullaby that soothes your nerves.",
    "The forest seems to pulse with life as every gust of wind and ray of moonlight imbues the night with a sense of secret purpose.",
    "You catch a fleeting glimpse of a shadow darting between the trees, igniting your curiosity about what might be hidden beyond.",
    "Intricate patterns of light and dark dance on the forest floor, as if the very essence of nature is painting a masterpiece before your eyes.",
    "A delicate, refreshing rain begins to fall, each droplet reflecting myriad colors and carrying whispers of hidden lore.",
    "In the distance, a flicker of movement suggests that a massive, enigmatic creature is silently observing you from afar.",
    "The fragrance of blooming wildflowers mingles with the rich aroma of wet soil, offering a brief, comforting respite from the night's mystery.",
    "An inexplicable feeling of déjà vu overwhelms you as the forest subtly shifts, revealing long-forgotten paths and secret glens.",
    "The branches overhead sway in unison as if orchestrated by an unseen conductor, filling the air with a mysterious energy.",
    "A shimmering veil of mist descends, blurring the boundaries between reality and dreams, leaving you to question what is real.",
    "An ancient stone archway appears among the trees, its weathered carvings hinting at rituals and legends of old.",
    "A sudden burst of static-like energy crackles in the air, making your hair stand on end as you sense powerful magic at work.",
    "Flickers of firefly light dart around you in a chaotic dance, creating a mesmerizing spectacle that distracts and delights.",
    "The soft murmur of a hidden waterfall reaches your ears, its rhythmic song drawing you toward its mysterious source.",
    "A swirling vortex of leaves and mist appears for a moment before dissipating, leaving behind a lingering sense of wonder.",
    "A spectral figure seems to float between the trees, its form barely discernible as it silently glides through the night.",
    "A distant bell tolls slowly, each resonant peal echoing through the forest like a summons from another realm.",
    "A sudden flash of lightning illuminates the sky, revealing ancient, towering trees and fleeting glimpses of hidden ruins.",
    "A cool breeze carries with it the faint sound of a harp, its melancholic melody weaving through the trees and stirring long-forgotten memories.",
    "The forest floor is carpeted with a riot of fallen leaves in hues of gold, crimson, and amber, each step crunching with the promise of change.",
    "A mysterious fog rolls in from the distant hills, obscuring your path and filling the air with an intoxicating, eerie calm.",
    "You notice that the forest seems to hold its breath, as if awaiting an unseen event that will alter its very nature.",
    "A sudden, gentle snowfall begins, each flake dancing in the moonlight and blanketing the world in a serene silence.",
    "A cluster of vibrant wild berries catches your eye, their colors too vivid to be natural—perhaps a hidden reward or a perilous trap.",
    "The sound of distant drums and chanting reaches you, a primal rhythm that seems to awaken ancient spirits in the woods.",
    "A luminous orb of light hovers silently in the air before darting away into the darkness, leaving you with a sense of both awe and apprehension.",
    "The wind brings with it a faint echo of laughter and sorrow intertwined, as if the forest itself is reminiscing about a bygone era.",
    "An intricate network of spiderwebs, glistening with dew, spans between the trees—a delicate reminder of nature’s fragile balance.",
    "A sudden rustling in the underbrush reveals a hidden glade where time seems to slow down, inviting you to pause and reflect."
  ];
  return events[Math.floor(Math.random() * events.length)];
}

module.exports = getRandomEvent;